#!bin/bash

# Function to print help message
print_help() {
    echo "Usage: ord [OPTIONS] SEARCH_TERM"
    echo "Options:"
    echo "  -f    Search Faroese to English (default)"
    echo "  -e    Search English to Faroese"
    echo "  -h    Display this help message"
    exit 1
}

# Function to convert string to lowercase
to_lowercase() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

# Default behavior is searching Faroese to Faroese
search_dir="fo-fo"

# Parse options
while getopts ":efh" opt; do
    case $opt in
        f)
            search_dir="fo-en"
            ;;
        e)
            search_dir="en-fo"
            ;;
        h)
            print_help
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            print_help
            ;;
    esac
done

# Shift the options to access the positional argument (SEARCH_TERM)
shift "$((OPTIND - 1))"

# Check if SEARCH_TERM is provided
if [ -z "$1" ]; then
    echo "Search term not provided."
    print_help
fi

# Convert the search term to lowercase and extract the first letter
search_term="$1"
search_term_lowercase=$(to_lowercase "$search_term")
first_letter=$(echo "$search_term_lowercase" | cut -c 1)

# Search the TSV file and print the description
echo "Orðið: $1"

description=$(grep -m 1 -i "^$search_term_lowercase" "$search_dir/${first_letter}_words_combined.tsv" | cut -f 2)
if [ -n "$description" ]; then
    # Split and print the description on separate lines
    if [[ "$description" =~ [0-9] ]] ; then
        echo "$description" | awk -F'[0-9]' '{ for(i=2; i<=NF; i++) print $i }'
    else
        echo "$description"
    fi
else
    echo "Word not found."
fi
